services:
    Gomobile\GomobileNOsixBundle\Core\GomobileNOsix:
        public: true
        arguments:
            - "%gomobile_n_osix.login%"
            - "%gomobile_n_osix.password%"
            - "%gomobile_n_osix.is_local%"